INSERT INTO CATEGORY(ID, NAME) VALUES (1, 'Dog');
INSERT INTO CATEGORY(ID, NAME) VALUES (2, 'Cat');
INSERT INTO CATEGORY(ID, NAME) VALUES (3, 'Snake');


-- INSERT INTO PET (ID, NAME, STATUS, CATEGORY_ID) VALUES (4, 'CATTY', 'AVAILABLE', 3);


